import { ActionType, ActionPriority } from '@sentinel/schemas';

export const ACTION_PRIORITY_WEIGHTS: Record<ActionPriority, number> = {
  EMERGENCY: 5,
  CRITICAL: 4,
  HIGH: 3,
  MEDIUM: 2,
  LOW: 1,
};

export const DEFAULT_ACTION_PRIORITIES: Record<ActionType, ActionPriority> = {
  STOP_WORK: 'EMERGENCY',
  EMERGENCY_PROTECTIVE_ACTION: 'EMERGENCY',
  EMERGENCY_ESCALATION: 'EMERGENCY',
  SUPERVISOR_ACK_REQUIRED: 'CRITICAL',
  ESCALATE: 'CRITICAL',
  MODIFY_WORK: 'HIGH',
  RELOCATE_TO_COOLING: 'HIGH',
  RELOCATE: 'HIGH',
  RECOVERY_BREAK: 'HIGH',
  MANDATORY_REST: 'HIGH',
  SUPERVISOR_REVIEW: 'HIGH',
  SUPERVISOR_ALERT: 'HIGH',
  SHADE_RECOMMENDATION: 'MEDIUM',
  SHADED_BREAK: 'MEDIUM',
  HYDRATION_REMINDER: 'LOW',
  MONITOR: 'LOW',
};

export const ACTION_REST_MINUTES: Partial<Record<ActionType, number>> = {
  STOP_WORK: 60,
  EMERGENCY_PROTECTIVE_ACTION: 60,
  EMERGENCY_ESCALATION: 60,
  MODIFY_WORK: 30,
  RELOCATE_TO_COOLING: 25,
  RELOCATE: 25,
  RECOVERY_BREAK: 20,
  MANDATORY_REST: 20,
  SHADE_RECOMMENDATION: 10,
  SHADED_BREAK: 10,
  HYDRATION_REMINDER: 0,
  MONITOR: 0,
};
