/**
 * Standardized Machine-Readable Reason Codes
 * Section 23 of Master Build Reference v2.0
 */

export const REASON_CODES = {
  // Environmental
  EXTREME_AMBIENT_HEAT: 'EXTREME_AMBIENT_HEAT',
  HIGH_THERMAL_LOAD: 'HIGH_THERMAL_LOAD',
  HEAT_RISE: 'HEAT_RISE',
  ELEVATED_HUMIDITY: 'ELEVATED_HUMIDITY',
  HIGH_SOLAR_EXPOSURE: 'HIGH_SOLAR_EXPOSURE',

  // Exposure & Work
  LONG_EXPOSURE: 'LONG_EXPOSURE',
  HIGH_TASK_INTENSITY: 'HIGH_TASK_INTENSITY',
  ELEVATED_WORKER_MODIFIER: 'ELEVATED_WORKER_MODIFIER',
  LOW_RECOVERY: 'LOW_RECOVERY',
  RECENT_RECOVERY_APPLIED: 'RECENT_RECOVERY_APPLIED',

  // Zone Clustering
  ZONE_CLUSTER_DENSITY: 'ZONE_CLUSTER_DENSITY',

  // Data Quality & Freshness
  DATA_STALE: 'DATA_STALE',
  DATA_AGING: 'DATA_AGING',
  MISSING_ENVIRONMENT_FIELD: 'MISSING_ENVIRONMENT_FIELD',
  UNCERTAIN_DATA_CONFIDENCE: 'UNCERTAIN_DATA_CONFIDENCE',

  // Policy & Guardrails
  GUARDRAIL_EMERGENCY_OVERRIDE: 'GUARDRAIL_EMERGENCY_OVERRIDE',
  POLICY_THRESHOLD_BREACH: 'POLICY_THRESHOLD_BREACH',
  UNACKNOWLEDGED_CRITICAL_ESCALATION: 'UNACKNOWLEDGED_CRITICAL_ESCALATION',
  NORMAL_OPERATING_LIMITS: 'NORMAL_OPERATING_LIMITS',

  // State Transitions
  RISK_ESCALATION: 'RISK_ESCALATION',
  RISK_DEESCALATION: 'RISK_DEESCALATION',
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
