import { Site } from '@sentinel/schemas';

export const PHOENIX_CONSTRUCTION_SITES: Site[] = [
  {
    site_id: 'PHX-SITE-01',
    name: 'Sky Harbor Air Logistics Hub',
    latitude: 33.4352,
    longitude: -112.0101,
    zone_id: 'ZONE-A-TARMAC',
    worker_count: 120,
    cooling_resources: {
      shade_stations: 6,
      water_points: 12,
      misting_fans: 8,
      ac_trailers: 2,
    },
    emergency_policy_id: 'OSHA_NIOSH_PHX_V1',
  },
  {
    site_id: 'PHX-SITE-02',
    name: 'Downtown 7th St High-Rise Tower',
    latitude: 33.4484,
    longitude: -112.0740,
    zone_id: 'ZONE-B-URBAN-CANYON',
    worker_count: 150,
    cooling_resources: {
      shade_stations: 8,
      water_points: 16,
      misting_fans: 10,
      ac_trailers: 3,
    },
    emergency_policy_id: 'OSHA_NIOSH_PHX_V1',
  },
  {
    site_id: 'PHX-SITE-03',
    name: 'Scottsdale Desert Ridge Commercial Center',
    latitude: 33.6846,
    longitude: -111.9261,
    zone_id: 'ZONE-C-DESERT-RIDGE',
    worker_count: 85,
    cooling_resources: {
      shade_stations: 4,
      water_points: 8,
      misting_fans: 6,
      ac_trailers: 2,
    },
    emergency_policy_id: 'OSHA_NIOSH_PHX_V1',
  },
  {
    site_id: 'PHX-SITE-04',
    name: 'West Valley Solar Array Infrastructure',
    latitude: 33.3980,
    longitude: -112.4402,
    zone_id: 'ZONE-D-OPEN-SOLAR',
    worker_count: 95,
    cooling_resources: {
      shade_stations: 5,
      water_points: 10,
      misting_fans: 4,
      ac_trailers: 2,
    },
    emergency_policy_id: 'OSHA_NIOSH_PHX_V1',
  },
  {
    site_id: 'PHX-SITE-05',
    name: 'Tempe Innovation Corridor Tech Campus',
    latitude: 33.4255,
    longitude: -111.9400,
    zone_id: 'ZONE-E-CAMPUS-TECH',
    worker_count: 50,
    cooling_resources: {
      shade_stations: 3,
      water_points: 6,
      misting_fans: 4,
      ac_trailers: 1,
    },
    emergency_policy_id: 'OSHA_NIOSH_PHX_V1',
  },
];
